version: 0.2
env:
  variables:
    NVM_DIR: /root/.nvm
    NODE_VERSION: 8.9
    DEPLOYMENT_REF: refs/heads/master
phases:
  install:
    commands:
      - chmod +x build_scripts/*.sh
      - bash build_scripts/install.sh
      - bash build_scripts/retrieve_git_meta.sh
  pre_build:
    commands:
      - bash build_scripts/pre_build.sh
  build:
    commands:
      - bash build_scripts/build.sh
